/**
 * This file is part of Niowire.
 *
 * Niowire is free software: you can redistribute it and/or modify it under the
 * terms of the Lesser GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * Niowire is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the Lesser GNU General Public License for more
 * details.
 *
 * You should have received a copy of the Lesser GNU General Public License
 * along with Niowire. If not, see <http://www.gnu.org/licenses/>.
 */
package io.niowire;

/**
 * This is the common exception for all Niowire exceptions (except runtime
 * exceptions. All exceptions generated by Niowire which go out through the
 * public API will be wrapped in an instance of this class.
 *
 * @author Trent Houliston
 */
public class NiowireException extends Exception
{

	public NiowireException()
	{
		super();
	}

	public NiowireException(String message)
	{
		super(message);
	}

	public NiowireException(String message, Exception cause)
	{
		super(message, cause);
	}

	public NiowireException(Exception cause)
	{
		super(cause);
	}
}
